name: Run windows

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        shells: [cmd, bash]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: set up node js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Build
        run: npm install -g cli-npm-poc
        shell: ${{ matrix.shells }}
      - name: check version
        run: npm -v
        shell: ${{ matrix.shells }}
      - name: init
        run: cli-npm-poc init
        shell: ${{ matrix.shells }}
