name: Run windows

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            { name: windows-latest, shell: cmd },
            { name: ubuntu-latest, shell: bash },
          ]
    runs-on: ${{ matrix.os.name }}
    steps:
      - uses: actions/checkout@v3
      - name: set up node js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Build
        run: npm install -g cli-npm-poc
        shell: ${{ matrix.os.shell }}
      - name: check version
        run: npm -v
        shell: ${{ matrix.os.shell }}
      - name: init
        run: cli-npm-poc init
        shell: ${{ matrix.os.shell }}
